### ISSUE TITLE
Are the snapshots incremental?

### ISSUE THREAD

**Issue by k----n** [NAIST-SE/DevGPT#3]
For example, is `snapshot_20230824` a subset of `snapshot_20230831`?

I am wondering because by combining all the `ChatGPT_Link_Sharing.csv`, there are 2661 unique ChatGPT links vs the 2345 found in `snapshot_20230831`.

**Comment by markxiaotao** [comment]
While data should logically be incremental, there are factors that could lead to inconsistencies across snapshots.  Developers may remove their mentions in GitHub artifacts later, where snapshot 20230831 only indicates we obtained the data on August 31, 2023. It will not guarantee the data will be consistent through snapshots. Another [threat](https://github.com/NAIST-SE/DevGPT#github-graphql-and-rest) is that

> It's worth noting that the total count varies upon each API/[Webpage access](https://github.com/search?q=%22https%3A%2F%2Fchat.openai.com%2Fshare%2F%22&type=commits) in the GitHub, which leads to inconsistent results compared to the GitHub website.

Given these considerations, it's advisable to primarily rely on the most recent snapshot for analysis. Older snapshots can serve as a fallback, particularly for recovering broken ChatGPT links, but should not be considered a definitive source.
