### ISSUE TITLE
Some lines of pr_sharings have "CommitShas" written as "CommitSha" 

### ISSUE THREAD

**Issue by diegoandrade-iuv** [NAIST-SE/DevGPT#4]
Hi,

when I was trying to use the pr_sharings, I noticed that some lines of this dataset have "CommitShas", as described on the readme, written as "CommitSha".

**Comment by markxiaotao** [comment]
Thank you for raising this issue, it is caused by inconsistent naming from different sources. We have made it consistent in the next release https://zenodo.org/record/8436454 
https://github.com/NAIST-SE/DevGPT/commit/35d906d957026f3db282b19dcc5074e399010725
